/**
 * Investment SharedDef server-message network-ids (`808E206C`, 56 rows).
 * Cracked names via FNV-1.
 */
export enum e_server_message_network_id {
  _server_message_network_id_director_get_activity_list = 101,
  _server_message_network_id_director_enter_orbit = 104,
  _server_message_network_id_director_complete_bink_activity = 105,
  _server_message_network_id_fetch_account = 201,
  _server_message_network_id_fetch_character = 202,
  _server_message_network_id_fetch_item = 203,
  _server_message_network_id_fetch_time = 204,
  _server_message_network_id_fetch_universe = 205,
  _server_message_network_id_fetch_family = 206,
  _server_message_network_id_fetch_account_family_versions = 207,
  _server_message_network_id_incident_miss_enemy = 303,
  _server_message_network_id_activity_host_incident = 304,
  _server_message_network_id_inventory_destroy_item = 401,
  _server_message_network_id_inventory_perform_item_action = 402,
  _server_message_network_id_inventory_equip_item = 403,
  _server_message_network_id_inventory_unequip_item = 404,
  _server_message_network_id_login_create_character = 501,
  _server_message_network_id_login_delete_character = 502,
  _server_message_network_id_login_account = 503,
  _server_message_network_id_login_character = 504,
  _server_message_network_id_signout_character = 505,
  _server_message_network_id_customize_character = 506,
  _server_message_network_id_loot_pickup_item = 601,
  _server_message_network_id_profile_set_account_profile = 701,
  _server_message_network_id_profile_set_character_profile = 702,
  _server_message_network_id_talent_grid_activate_step = 801,
  _server_message_network_id_talent_grid_binary_swap = 802,
  _server_message_network_id_talent_grid_bind_ability = 803,
  _server_message_network_id_vendor_buy_item = 901,
  _server_message_network_id_vendor_buyback_item = 902,
  _server_message_network_id_vendor_sell_item = 903,
  _server_message_network_id_server_debug_failure = 1101,
  _server_message_network_id_server_debug_latency = 1102,
  _server_message_network_id_server_debug_crash = 1103,
  _server_message_network_id_cheat_advance_time = 1201,
  _server_message_network_id_cheat_character_add_item = 1202,
  _server_message_network_id_cheat_character_add_progression = 1203,
  _server_message_network_id_cheat_character_set_debug_state = 1205,
  _server_message_network_id_cheat_character_set_progression = 1206,
  _server_message_network_id_cheat_character_set_unlock_flag = 1207,
  _server_message_network_id_cheat_character_clear_progression_limits = 1208,
  _server_message_network_id_cheat_character_set_debug_time = 1209,
  _server_message_network_id_cheat_character_invoke_daily_reset = 1210,
  _server_message_network_id_cheat_character_invoke_weekly_reset = 1211,
  _server_message_network_id_cheat_character_delete_item = 1212,
  _server_message_network_id_cheat_character_replace_equipped_item = 1213,
  _server_message_network_id_cheat_activity_complete = 1214,
  _server_message_network_id_cheat_character_reset = 1215,
  _server_message_network_id_cheat_character_set_incident_accumulator = 1216,
  _server_message_network_id_cheat_set_clan_name = 1217,
  _server_message_network_id_cheat_incident = 1218,
  _server_message_network_id_activity_host_start_activity = 1301,
  _server_message_network_id_activity_host_complete_activity = 1302,
  _server_message_network_id_activity_host_get_activity_host_startup_options = 1303,
  _server_message_network_id_activity_host_get_character_data = 1304,
  _server_message_network_id_update_offers = 1401,
}
